language: python

python:
  - "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-{pip,pandas,matplotlib,numpy}

install:
  - pip install -r testsuite/requirements.txt
  - python setup.py install

script: 
  - make test

notifications:
  slack: tessfpe:2IRXkGdeeDMrkQAGhWRaCJww

