language: python

python:
  - "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y geda-{gschem,gnetlist} a2ps texlive-latex-{base,extra,recommended} python-{pip,sphinx,pandas,matplotlib,numpy}

install: "pip install -r testsuite/requirements.txt"

script: 
  - make test
  - make clean manual

notifications:
  slack: tessfpe:2IRXkGdeeDMrkQAGhWRaCJww
